name: 'ci-dotenv'
description: 'Export environment variables from .env file'

inputs:
   path:
    description: 'Path to the .env file (including file name)'
    default: '.env'
    required: true

   mask-variables:
    description: 'Consider the variables as secrets'
    required: false
    default: 'false'

outputs:
  variables:
    description: 'Exported environment variables'

runs:
  using: 'node16'
  main: 'dist/index.js'
